define("lib.external.moodular",["jquery-1.4"],function(b){b.fn.moodular=function(a){var c=null,d=b.extend({},b.fn.moodular.defaults,a),e=b.extend({},b.fn.moodular.controls),g=b.extend({},b.fn.moodular.effects);this.each(function(){c=new h(this,d,e,g);b(window).bind("resize",function(){c._resize()})});return d.api?c:null};b.moodular=function(a,c,d,e){this.e=b(a);if(c.random){var g=this.e.children(b("> "+c.item));g.sort(function(){return Math.round(Math.random())-0.5});this.e.remove(b("> "+c.item));
for(var f=0;f<g.length;f++)this.e.append(g[f])}c.continuous&&b(a).html(b(a).html()+b(a).html());this.aItems=null;this.current=this.nbItems=0;this.locked=false;this.dep=0;this.timerMoving=null;this.opts=c;this.controls=d;this.effects=e;this.direction=c.direction=="left"||c.direction=="top"?"next":"prev";this.pos=c.direction=="left"||c.direction=="right"?"left":"top";this.dir=c.direction=="right"||c.direction=="bottom"?-1:1;this.vertical=this.pos=="left"?false:true;this._init()};var h=b.moodular;h.fn=
h.prototype={moodular:"2.3"};h.fn.extend=h.extend=b.extend;h.fn.extend({_init:function(){var a=this;this._resize();this.e.wrap('<div class="carousel"><div class="carousel_viewport"></div></div>');this.e.parent().css({position:"relative",overflow:"hidden",width:this.e.width(),height:this.e.height()});this.e.css({position:"absolute"});var c=0;b("> "+this.opts.item,this.e).each(function(){c+=this.vertical?parseInt(b(this).outerHeight(true)):parseInt(b(this).outerWidth(true))});this.e.css(this.vertical?
"height":"width",c+"px");this.aItems=b("> "+this.opts.item,this.e);this.nbItems=this.aItems.length;this.opts.continuous||(this.nbItems*=2);var d=this.opts.controls.split(" "),e;for(e=0;e<d.length;e++)b.isFunction(this.controls[d[e]])&&this.controls[d[e]](this);d=this.opts.effects.split(" ");for(e=0;e<d.length;e++)b.isFunction(this.effects.init[d[e]])&&this.effects.init[d[e]](this);if(this.opts.startOn){this.speed=this.opts.speed;this.opts.speed=1;this.moveTo(this.opts.startOn)}if(this.opts.auto)this.timerMoving=
setTimeout(function(){a._animate("next")},a.opts.dispTimeout)},_animate:function(a){a=a==undefined?this.direction:a;if(!this.locked){if(this.opts.fireEvents){var c=b.Event("beforeAnimate");c.direction=a;c.realPos=this._realpos(this);b(this).trigger(c)}this.locked=true;clearTimeout(this.timerMoving);this.dep=this.dep==0?this.opts.scroll:this.dep;if(this.dir==-1)if(a=="next")a="prev";else if(a=="prev")a="next";if(a!="next")this.dep*=-1;c=true;if(!this.opts.continuous)if(a=="next"){if(this.current>=
this.nbItems/2-1)this.locked=c=false}else if(this.current<=0)this.locked=c=false;c&&this._beforeMoving()}this.opts.promoCarousel&&this.fadeHeaderOut()},_beforeMoving:function(){var a=this.opts.effects.split(" "),c;for(c=0;c<a.length;c++)if(b.isFunction(this.effects.before[a[c]]))this.effects.before[a[c]](this,this.dep<0?-1:1);if(this.dep<0&&this.opts.continuous){for(c=a=0;c<Math.abs(this.dep);c++){var d=b("> "+this.opts.item+":last",this.e);a+=parseInt(d.css(this.vertical?"height":"width"));b("> "+
this.opts.item+":last",this.e).remove();this.e.prepend(d)}this.e.css(this.pos,-a)}this._move()},_move:function(){var a=this;if(b.isFunction(this.opts.move))this.opts.move(this,function(){a._afterMoving()});else{var c=0,d;if(this.dep>0)for(d=0;d<this.dep;d++)c+=this.vertical?parseInt(this.aItems.eq(this._realpos(this.current)+d).outerHeight(true)):parseInt(this.aItems.eq(this._realpos(this.current)+d).outerWidth(true));else if(!(!this.opts.continuous&&this.current<=0))for(d=0;d<Math.abs(this.dep);d++)c+=
this.vertical?parseInt(this.aItems.eq(this._realpos(this.current)-d).outerHeight(true)):parseInt(this.aItems.eq(this._realpos(this.current)-d).outerWidth(true));this.e.css(this.pos)=="auto"&&this.e.css(this.pos,0);c=parseInt(this.e.css(this.pos))+(this.dep>0?-1:1)*c;if(!this.opts.continuous){if(c>0)c=0;if(this.vertical){if(parseInt(this.e.height())+c<parseInt(this.e.parent().height()))c=parseInt(this.e.parent().height())-parseInt(this.e.height())}else if(parseInt(this.e.width())+c<parseInt(this.e.parent().width()))c=
parseInt(this.e.parent().width())-parseInt(this.e.width())}this.vertical?this.e.stop(true,true).animate({top:parseInt(c)+"px"},this.opts.speed,this.opts.easing,function(){a._afterMoving()}):this.e.stop(true,true).animate({left:parseInt(c)+"px"},this.opts.speed,this.opts.easing,function(){a._afterMoving()})}},_afterMoving:function(){var a;if(this.dep>0&&this.opts.continuous){for(a=0;a<this.dep;a++){var c=b("> "+this.opts.item+":first",this.e);b("> "+this.opts.item+":first",this.e).remove();this.e.append(c)}this.e.css(this.pos,
0)}var d=this;this.current+=this.dep;this.current=this.current==-1?this.opts.continuous?this.nbItems-1:0:this.current==this.nbItems?0:this._realpos(this.current);this.dep=0;this.locked=false;c=this.opts.effects.split(" ");for(a=0;a<c.length;a++)b.isFunction(this.effects.after[c[a]])&&this.effects.after[c[a]](this);for(a=0;a<this.opts.callbacks.length;a++)this.opts.callbacks[a](this);c=this.opts.controls.split(" ");for(a=0;a<c.length;a++)b.isFunction(this.controls.callback[c[a]])&&this.controls.callback[c[a]](this);
if(this.opts.startOn)this.opts.speed=this.speed;if(this.opts.auto)this.timerMoving=setTimeout(function(){d._animate("next")},this.opts.dispTimeout);if(this.opts.promoCarousel){this.changeHeader();this.fadeHeaderIn()}},_realpos:function(a){if(a<0)a=this.nbItems/2-a;return a<this.nbItems/2?a:a-this.nbItems/2},_resize:function(){b("> "+this.opts.item,this.e).css(this.vertical?"height":"width");b("> "+this.opts.item,this.e).each(function(){this.vertical?b(this).height(b(this).height()):b(this).width(b(this).width())})},
reanimate:function(){if(!this.opts.auto){this.locked=false;this.opts.auto=true;var a=this;this.timerMoving=setTimeout(function(){a._animate("next")},this.opts.dispTimeout)}},start:function(){if(!this.opts.auto){this.opts.auto=true;this._animate("next")}return false},stop:function(){clearTimeout(this.timerMoving);return this.opts.auto=false},fadeHeaderOut:function(){b("#promo_title_link").animate({opacity:[0,"swing"]})},fadeHeaderIn:function(){b("#promo_title_link").animate({opacity:[1,"swing"]})},
changeHeader:function(){var a={},c=this.aItems[this._realpos(this.current)];a.text="Top stories";a.url="http://www.bbc.com/";a.rev="promo|homepage|na|r|t|i|text|headline";if(b(c).hasClass("news")){a.text="Top News story";a.url=b(c).find("a").attr("href")}if(b(c).hasClass("sport")){a.text="Top Sport story";a.url=b(c).find("a").attr("href")}if(b(c).hasClass("travel")){a.text="Top Travel story";a.url=b(c).find("a").attr("href")}if(b(c).hasClass("custom"))if("undefined"!=typeof wwhomepage.customPromoHeaders[b(c).find("dt a").attr("href")]){a.text=
wwhomepage.customPromoHeaders[b(c).find("dt a").attr("href")].promo_type;a.url=wwhomepage.customPromoHeaders[b(c).find("dt a").attr("href")].promo_url}a=b('<a title="Go to '+a.text+'" rev="'+a.rev+'" href="'+a.url+'" id="promo_title_link" style="opacity:1;">'+a.text+"</a>");a.css("opacity",0);b("#promo_title").html(a)},next:function(){this._animate("next");return false},prev:function(){this._animate("prev");return false},getCurrent:function(){return this._realpos(this.current)},moveTo:function(a){if(a>
this.nbItems/2)a=this.nbItems/2-1;this.dep=parseInt(a)-parseInt(this.current);this.dep!=0&&this._animate("next");return false}});b.fn.moodular.defaults={item:"li",controls:"",effects:"",easing:"",auto:true,continuous:true,speed:2E3,direction:"left",scroll:1,startOn:0,dispTimeout:1E3,callbacks:[],random:false,api:false};b.fn.moodular.controls={callback:{}};b.fn.moodular.effects={init:{},before:{},after:{}};b.extend(b.fn.moodular.controls,{previewNav:function(a){if(a.e.context.id===undefined||a.e.context.id===
"")throw new Error("the wrapper for the carousel items must have an id to use the preview nav component");var c=a.e.context.id,d=false,e=false,g=b('<div class="nav_left"><span class="hide">Left</span><div class="image"><img width="71" height="40" src=""/></div></div>'),f=b('<div class="nav_right"><span class="hide">Right</span><div class="image"><img width="71" height="40" src=""/></div></div>'),j=a.opts.auto&&a.opts.playPause?b('<div class="autoplay nav_pause"><span class="hide"></span></div>'):
b('<div class="autoplay nav_play"><span class="hide"></span></div>'),l=b('<ol id="'+c+'_items" class="carousel_itemList"></ol>'),m=function(k){k=k==="play"||k===true?"play":"pause";switch(k){case "play":j.attr("class","autoplay nav_pause");a.start();a.manualPlay=true;break;case "pause":j.attr("class","autoplay nav_play");a.stop();break;default:throw new Error("not a valid state");}},o=function(k,n){if(!d){d=true;n==="fadein"&&k.fadeIn(200,function(){d=false});n==="fadeout"&&k.fadeOut(200,function(){e=
d=false})}},p=function(k){o(k,"fadein");if(e===false)e=setTimeout(function(){o(k,"fadeout")},2E3)};g.bind("click",function(){a.prev();m("pause");return false}).mouseover(function(){b(this).css("width","123px").css("cursor","pointer").addClass("hover")}).mouseout(function(){b(this).css("width","47px").css("cursor","default").removeClass("hover")});f.bind("click",function(){a.next();m("pause");return false}).mouseover(function(){b(this).css("width","123px").css("cursor","pointer").addClass("hover");
b.browser.msie&&b.browser.version==="6.0"&&b(this).addClass("nav_right_hover")}).mouseout(function(){b(this).css("width","47px").css("cursor","default").removeClass("hover");b.browser.msie&&b.browser.version==="6.0"&&b(this).removeClass("nav_right_hover")});if(a.opts.playPause){j.css("display","none").bind("click",function(){m(!a.opts.auto);b(this).addClass("hover")}).mouseover(function(){b(this).css("cursor","pointer").addClass("hover");p(j);d=true}).mouseout(function(){b(this).css("cursor","default").removeClass("hover");
d=false});a.e.parent().parent().append(j)}a.e.parent().parent().append(g).append(f);b("#"+c).bind("mousemove",function(){p(j)});a.e.parent().parent().append(l);g="";for(f=0;f<a.nbItems/2;f++)g+='<li class="carousel_itemList_li" rel="'+f+'"><span class="hide">'+(f+1)+"</span></li>";b("#"+c+"_items",a.e.parent().parent()).html(g);b("#"+c+"_items li",a.e.parent().parent()).css("cursor","pointer").click(function(){if(a.locked)a.locked=false;else{b("#"+c+"_items li.active").removeClass("active");a.moveTo(b(this).attr("rel"));
b(this).addClass("active");m("pause")}return false});b(".carousel_itemList_li:first").addClass("active");a.controls.callback.previewNav(a)},callback:{previewNav:function(a){var c=a.e.context.id,d=function(f,j){var l,m;m=j/2-1;l=f===0?m:f-1;if(f===j-1)l=m-1;return l},e=function(f,j){var l;l=f===j/2-1?0:f+1;if(f===j-1)l=0;return l},g=function(f){return b(a.aItems[f]).find("img").attr("src")};b("#"+c+"_items li.active").removeClass("active");b("#"+c+"_items li[rel$="+(a.current===a.nbItems-1?a.nbItems/
2-1:a.current)+"]").addClass("active");b("#"+a.e.context.id).parent().parent().find(".nav_right .image img").attr("src",g(e(a.current,a.aItems.length)));b("#"+a.e.context.id).parent().parent().find(".nav_left .image img").attr("src",g(d(a.current,a.aItems.length)))}}});b.extend(b.fn.moodular.effects.after,{singleRevolution:function(a){if(a.manualPlay!==true&&a.opts.auto===true&&a.current===0){a.e.parent().parent().find(".nav_pause").removeClass("nav_pause").addClass("nav_play");a.stop()}}});return b});
define("wwhomepage.ui.carouselfactory",["lib.external.moodular"],function(b){return{createCarousel:function(h,a){return b(h).moodular(a)}}});
define("wwhomepage.utils.popup",["jquery-1.4"],function(b){return{registerPopup:function(h,a){h=b(h);var c=b(h).attr("href");a=a||{};var d=a.windowName||"popup",e=[],g="",f={};f.toolbar=a.toolbar||"0";f.scrollbar=a.scrollbars||"0";f.location=a.location||"0";f.statusbar=a.statusbar||"0";f.menubar=a.menubar||"0";f.directories=a.directories||"0";f.resizable=a.resizable||"0";f.width=a.width||"100";f.height=a.height||"100";f.left=a.left||"100";f.top=a.top||"100";for(setting in f)e.push(setting+"="+f[setting]);
g=e.join(",");b(h).bind("click",function(j){window.open(c,d,g);j.preventDefault();j.stopPropagation()})}}});
define("wwhomepage.ui.weather",["jquery-1.4"],function(b){var h=function(){};h.prototype={domEl:null,editButton:null,searchPanel:null,defaultCleared:false,moduleId:null,contentBlockId:null,inputDefaultText:null,editButtonText:"Edit my location",closeButtonText:"Close",resultsText:"Select an option below to select your location",noResultsText:"Location not found",init:function(a,c){this.opts=c;this.domEl=b(a);this.domEl.find(".weatherforecast h3").after('<span class="edit">'+this.editButtonText+"</span>");
this.editButton=this.domEl.find(".weatherforecast .edit");this.searchPanel=this.domEl.find(".weatherforecast .searchPanel");this.inputDefaultText=this.searchPanel.find('[name="value"]').val();this.moduleId=this.searchPanel.find('form [name="module"]').val();this.contentBlockId=this.searchPanel.find('form [name="contentBlock"]').val();this.defaultCleared=false;this.opts.autocomplete.enabled===true&&this.searchPanel.find("form").attr("autocomplete","off");a=this.readCookie("hploc");a!==null&&a!=""?
this.setAndUpdate("/customise?module=weather&action=set&value="+a):b("#weather_forecast").removeClass("weather_loading")},reset:function(){this.searchPanel.find(".searchPanelSearch").val(this.inputDefaultText);this.searchPanel.find(".results");this.defaultCleared=false},processResults:function(a){var c=this.searchPanel.find(".results"),d=c.find("ul"),e=c.find("p");d.empty();if(typeof a!="undefined"&&a.length>0){for(var g in a){var f=a[g],j=encodeURI("/customise?module=weather&action=set&value="+f.data.loc);
d.append('<li><a href="'+j+'">'+f.data.full_name+"</a>")}e.text(this.resultsText).removeClass("noResults")}else e.text(this.noResultsText).addClass("noResults");c.not(":visible")&&c.slideDown()},ajaxSearch:function(){var a=this.searchPanel.find("form"),c=this;b.ajax({type:a.attr("method"),url:a.attr("action"),data:{module:"weather",action:"search",value:a.find('[name="value"]').val()},dataType:"json",success:function(d){if(d.content.hasOwnProperty("locations"))c.processResults(d.content.locations);
else if(d.content.hasOwnProperty("forecast")){d=d.content.forecast.location;c.processResults([{data:{loc:d.id,site_name:d.siteName,full_name:d.siteName+", "+d.country}}])}else d.content===false&&c.processResults([])}})},setAndUpdate:function(a){var c=this;a=a.split("?");b.ajax({type:"GET",url:a[0],data:a[1],dataType:"json",success:function(d){b("#weather_forecast").removeClass("weather_loading");d=b(d.content.forecast.html);var e=["h3",".dayForecast",".detail"];for(i in e){c.domEl.find(e[i]).replaceWith(d.find(e[i]));
if(c.searchPanel.is(":visible")){c.searchPanel.slideUp();c.editButton.text(c.editButtonText);c.reset()}}},error:function(){b("#weather_forecast").removeClass("weather_loading")}})},setEventListeners:function(){this.editButton.bind("click",{self:this},function(c){c=c.data.self;if(c.searchPanel.is(":visible")){c.searchPanel.slideUp();c.editButton.text(c.editButtonText)}else{c.searchPanel.slideDown();c.editButton.text(c.closeButtonText);c.reset()}return false},false);var a=this.searchPanel.find("input");
a.bind("focus",{self:this},function(c){c=c.data.self;if(c.defaultCleared===false){b(this).val("");c.defaultCleared=true}return false},false);this.searchPanel.find("form").bind("submit",{self:this},function(c){c.data.self.ajaxSearch();return false},false);this.opts.autocomplete.enabled===true&&a.bind("keyup",{self:this},function(c){c=c.data.self;b(this).val().length>=c.opts.autocomplete.minLength&&c.ajaxSearch();return false},false);this.searchPanel.find(".results a").live("click",{self:this},function(c){c.data.self.setAndUpdate(this.href);
return false},false)},readCookie:function(a){a=a+"=";for(var c=document.cookie.split(";"),d=0;d<c.length;d++){for(var e=c[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(a)==0)return e.substring(a.length,e.length)}return null},renderWeather:function(a,c){this.init(a,c);this.setEventListeners()}};return h});
define("wwhomepage.ui.tabs",["jquery-1.4"],function(b){return{registerTabs:function(h){b(h+" .tab").click(function(a){tabs=b(h+" .tab");tabs.removeClass("selected");panels=b(h+" .panel");panels.removeClass("selected");eventElement=b(a.currentTarget);eventElement.addClass("selected");panelElement=eventElement.next();panelElement.addClass("selected");return false})}}});
define("wwhomepage.ui.drawers",["jquery-1.4"],function(b){var h=function(){};h.prototype={openDrawerId:0,numberOfDrawers:0,drawersLeft:[],init:function(a,c){this.opts=c;b(a).data("opts",c);this.numberOfDrawers=b(a).children().length;this.openDrawerId=this.numberOfDrawers-1;if("undefined"!=typeof this.opts.openDrawer)this.openDrawerId=this.opts.openDrawer;b(a).addClass("drawersEnabled");b(a+" .contentBlocks").addClass("drawer");!b(a+" .contentBlocks").css("-moz-transform")&&!b(a+" .contentBlocks").css("-webkit-transform")&&
!b(a+" .contentBlocks").css("layout-flow")&&!b(a+" .contentBlocks").css("-o-transform")&&b(a+" .contentBlocks").addClass("no-transform")},setOpenDrawer:function(a){for(var c=b(".drawer h2 a"),d=0,e=c.length;d<e;d++){var g=b(c[d]).parent().parent();text='<a class="handle" id="handle'+d+'" href="#"><span>'+b(c[d]).text().replace(/([a-zA-Z& ]+)(.+)/,"$1")+"</span></a>";g.prepend(text).attr("id",d);var f=a.drawerHandleWidth*d;if(this.openDrawerId<d)f=a.drawerHandleWidth*(d-1)+parseInt(a.drawerWidth);
else this.drawersLeft[d]=true;g.css("left",f+"px");if(this.openDrawerId==d)g.addClass("drawer-open");else if(!(b.browser.msie&&"6.0"==b.browser.version)){b("#"+d+" h2").css({opacity:0});b("#"+d+" .contentBlock").css({opacity:0})}}},setEventListeners:function(){b(".handle").bind("click",{self:this},function(a){a=a.data.self;clickedDrawerId=parseFloat(b(this).attr("id").substring(6));if(a.drawersLeft[clickedDrawerId])a.animateRight(clickedDrawerId);else a.drawersLeft[clickedDrawerId]||a.animateLeft(clickedDrawerId);
return false},false)},animateRight:function(a){drawersToAnimateRight=[];for(x=a+1;x<=this.numberOfDrawers;x++){drawer=b("#"+x);if(1<=drawer.length&&this.drawersLeft[x]){drawersToAnimateRight.push(drawer);this.drawersLeft[x]=false}}this.fadeInOutDrawers(a);for(var c=0,d=drawersToAnimateRight.length;c<d;c++){var e={left:parseFloat(drawersToAnimateRight[c].css("left"))+(this.opts.drawerWidth-this.opts.drawerHandleWidth)+"px"};drawersToAnimateRight[c].animate(e,400,function(){b(this).addClass("drawer-right")})}this.toggleHandles(a)},
animateLeft:function(a){drawersToAnimateLeft=[];drawerIdsToAnimateLeft=[];this.drawersLeft[a]=true;for(drawerId=a-1;drawerId>=1;drawerId--){drawer=b("#"+drawerId);drawer.handleWidth=this.opts.drawerHandleWidth;if(1<=drawer.length&&!this.drawersLeft[drawerId]){drawersToAnimateLeft.push(drawer);drawerIdsToAnimateLeft.push(drawerId);this.drawersLeft[drawerId]=true}}this.fadeInOutDrawers(a);var c={left:parseFloat(b("#"+a).css("left"))-(this.opts.drawerWidth-this.opts.drawerHandleWidth)+"px"};b("#"+a).animate(c,
{step:function(d){b.each(drawersToAnimateLeft,function(e,g){g.css("left",d-g.handleWidth*(e+1))})},complete:function(){b(this).removeClass("drawer-right");b.each(drawersToAnimateLeft,function(d,e){e.removeClass("drawer-right")})}},400);this.toggleHandles(a)},fadeInOutDrawers:function(a){if(!(b.browser.msie&&"6.0"==b.browser.version)){b("#"+this.openDrawerId+" h2").animate({opacity:0},this.opts.drawerFadeOutContentSpeed);b("#"+this.openDrawerId+" .contentBlock").animate({opacity:0},this.opts.drawerFadeOutContentSpeed);
b("#"+a+" h2").animate({opacity:1},this.opts.drawerFadeInContentSpeed);b("#"+a+" .contentBlock").animate({opacity:1},this.opts.drawerFadeInContentSpeed)}},toggleHandles:function(a){this.showHandle(this.openDrawerId);this.hideHandle(a);this.openDrawerId=a},showHandle:function(a){b("#handle"+a).animate({opacity:1},400,function(){b(this).css("display","block")})},hideHandle:function(a){b("#handle"+a).animate({opacity:0},400,function(){b(this).css("display","none")})},renderDrawers:function(a,c){this.init(a,
c);this.setOpenDrawer(c);this.setEventListeners()}};return h});
define("wwhomepage.ui.tennisresults",["jquery-1.4"],function(b){var h=function(){};h.prototype={init:function(a){var c=b(a),d=c.find(a+"_mensScores"),e=c.find(a+"_womensScores");if(d&&e)if(d.hasClass("noresults")&&e.hasClass("noresults")){d.hide();e.hide()}else{updated=false;footer=c.find(a+"_footerLinks");updateDom=d.find(".updated");if(!updated&&updateDom.length){footer.append(updateDom.remove());updated=true}updateDom=e.find(".updated");if(!updated&&updateDom.length){footer.append(updateDom.remove());
updated=true}else updateDom.length&&updateDom.remove()}},render:function(a,c){this.init(a,c)}};return h});define("main",function(){});